[package]
name = "takpy"
version = "0.10.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "takpy"
crate-type = ["cdylib"]

[dependencies]
fast-tak = "0.4.2"
pyo3 = "0.28.0"
